name: STAGING

on:
  push:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Update Blobs
        uses: azure/cli@v1.0.0
        with:
          inlineScript: |
            az storage blob sync -c '$web' -s _output --exclude-pattern '*.json' --connection-string '${{ secrets.STAGING_AZURE_STORAGE_CONNECTION_STRING }}'

            az storage blob delete-batch -s '$web' --pattern '*.json' --connection-string '${{ secrets.
            STAGING_AZURE_STORAGE_CONNECTION_STRING }}'

            az storage blob upload-batch -d '$web' -s _output --pattern '*.json' --connection-string '${{ secrets.STAGING_AZURE_STORAGE_CONNECTION_STRING }}'

      - name: Purge CDN
        uses: azure/cli@v1.0.0
        with:
          inlineScript: |
            az login --service-principal -u http://myApp --password '${{ secrets.AZURE_LOGIN }}' --tenant '${{ secrets.AZURE_LOGIN_TENANT }}'

            az cdn endpoint purge -g jedwards -n 'jedwards-staging' --profile-name jedwards-staging --content-paths '/*'

            az logout

  deploy-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node Environment
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: "Resolve Project Dependencies Using Npm"
        shell: bash
        run: |
          pushd './functions'
          npm install
          npm run build --if-present
          npm run test --if-present
          popd

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: "jedwards-staging"
          package: "./functions"
          publish-profile:
            ${{ secrets.STAGING_AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
